name: Publish Docker Image
on: push

jobs:
  publish_image:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Kaniko build
      uses: aevea/action-kaniko@master
      with:
        image: ${{ env.DOCKERHUB_USERNAME }}/trac
        username: ${{ env.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_PASSWORD }}
