name: Unit Tests
on: push

jobs:
  run_unit_tests:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Run Tests
      run: python3 -m unittest discover -v Tuleap/RestClient/test
